void Main()
{
	var input = "tsgbzmgbonethreedrqzbhxjkvcnm3" +
"\n7qlpsnhbmnconeeight78" +
"\nprbqsfzqn57" +
"\nctrv3hmvjphrffktwothree" +
"\n9six9qbgcvljfvccdjslspprgonenine" +
"\neighteight9dnvcqznjvfpreight" +
"\none5sevenfour3" +
"\ngjgfiveonekzssz9c" +
"\none54" +
"\nrtsevenfourfive1rqhslone" +
"\nxkxfdhk25fourtwot8" +
"\nkjgcsncmeightdxdgkxfzqmmkg1351" +
"\n7qpnldcvgs" +
"\nreightwotz5" +
"\nnineqrtrsfsreightthreetworvrphxptlrbczxsix1" +
"\n1svfvgsfcssjpvhzr" +
"\n1seven174ndseight2" +
"\n56lrkxdfive" +
"\n2jvrgmmlninejf583" +
"\nfvsspqpt31" +
"\n3threemhjhvrvgkseven" +
"\neightoneoneeightttlpjqgnkndbnmppjsdhzdbhkhl12" +
"\nvxjgghc18dzbsssnssh" +
"\none2cgxdfbfhl3" +
"\n8ssfour997six6" +
"\n8onesrtcvqmxpzeighttwo6" +
"\n3twoptpvz5cbgpdrggdtwoseven" +
"\n35smnsnzxmdjtsns6sevenonethree" +
"\nfivetwoeightfdjpscncb41" +
"\nflkdknzdxtgdxcfqkn4mbh4tqvgdq" +
"\none3threethree" +
"\nsevenfourgdnxhsqq5one1" +
"\nkkrjgpm2sixeight24" +
"\nkrrhdhjqgmc5dv4" +
"\ncvlh16nineeight" +
"\n495five2nine1" +
"\ntzmcxvdtvxpmrcsevenfour15one" +
"\n2qvbrsxqsix45threeeight" +
"\npfmktwo29onensbfgdddfm2" +
"\n7xqjzxstvsthree" +
"\n37ninetwo3" +
"\n5vhtctxvjrvftwoone2six" +
"\nhbhxhjjl5twoqxmlprccr5" +
"\nninefour2foureight69" +
"\n1sevenmggmcxfcfdxptktsgcgsc" +
"\nfnkzsdjh3kqxpdvmkmvqqjcjn" +
"\ntwotcspvbvppqqntwo1hlcvppcpnv5" +
"\nxbfhpnkqbnxdfgbgtm5" +
"\n84tpzgonelnine6bzkx" +
"\nbgslbmdkfpbx6" +
"\nlqpfphxdtfourxbqdhrbcz2cmhtddsnkpgln" +
"\n7fourfzthreezhrjdjlvsix4lrrfv" +
"\n2seven3" +
"\nfourtdggtgsdm5" +
"\n1pbphhpsxbnqmfbxzone" +
"\ntskfvdph7mftvqpnvcj2oneninenine2" +
"\n3fiveeighttwothreeninenine" +
"\nseven687two1pdjbbprztwo" +
"\neightrslvddpmonejfive4hhqbdq" +
"\nxbhcqzx52eight52seventwo" +
"\nfbgpj8fourthreecqngmbbvkktlbss" +
"\nplckgsixeight6eight95bnrfonetwonej" +
"\n1nine97rtrtxhqnone2" +
"\ncntfouronerdsnn4lfcmhvlrq1five" +
"\nhrh34sixfourqqng7eightwot" +
"\nsixlfldl7qjsclxqfive15" +
"\nkhdfour17" +
"\nfrmcpx65" +
"\nfive6bjlbxkp7qthreethreecc3" +
"\n5four6qlmpsrdeightfour" +
"\n9lxdxgfrnlk4lsgbjnz9two" +
"\none7five2fvdqfqqn92xsxnblxvhdfcrz" +
"\nhmhmxvqljdgvvvdfour5one68zgm" +
"\n718" +
"\n3onefive43" +
"\nxgpqs5four267six" +
"\npqseven17nineninephpszgqzsixldhxmhzgf" +
"\nncxxlsqdkvc8fiverslzqtzhzltcmbkthreelkjjckxsvljvs" +
"\nnine6sixkrs" +
"\n5kcqpgfms" +
"\n1znbcrpxmjcsixeight" +
"\nsixtwo28eight59fql" +
"\n8nfcseven" +
"\n8five864sixfive" +
"\n8fzsvsrjmjxmc" +
"\nkftvseven6dcsfqtmtjvmgbrninefvv6" +
"\ntwoseven65" +
"\nnine58sjshtgtqlz" +
"\nlhjfzvlbtrfffour9eighteight73" +
"\n9crhmmqkrrfour" +
"\nthreeklhhtlmczn6thfkvdd" +
"\ndvjxkdgsnlds44kxs" +
"\n9gtvhrcphvnzbmckkeightfour" +
"\nfouronejtvrscxj9onethreelgslth" +
"\n86four" +
"\n4hvnqzfthree" +
"\n8qone9" +
"\nlnkngkxsflqsvm3threenine2seven3" +
"\n65five" +
"\n8529xdd5threeonexq" +
"\nsevenlthree1" +
"\n5sevennineflfivevgp" +
"\n6pmzqczjtlnfvgg1sevensix" +
"\nsixtwoone2" +
"\nkqrxsgtrrjsix9" +
"\n2twonebs" +
"\nfs9hmjmdmbhkskqvdb" +
"\n293" +
"\n9sevenbprbbnzqjbhfpcgnxjmflxgkvqgvc" +
"\nrkd58six" +
"\n5mbgfldv7rskkllhm" +
"\nfcjdzfjpvptdcxfltdddm7twornkskrnqnqv" +
"\nbkqzf51two8twoeight8" +
"\n2fivefour4777six8" +
"\nmzq67threetwonrqpcrptwo" +
"\n7bmkeightm8" +
"\nz6twoeight5threerfckddtc" +
"\nthreeninesixmtdc7xtjhvksjjc" +
"\n5fxffvhqzgtdlfdxdhsixnmjtvlq2five" +
"\nnqpsvzgql1" +
"\nsix3qljkjbfeight" +
"\nsgddglfjrtwoseven3" +
"\nrxzhvffr1rfxqpr" +
"\n7zjv5" +
"\n3tcsxlpxhsmnmg27" +
"\nlbqkvfxp8sevendcjlrfour7" +
"\ncxlvqldcjhhlzcvsix6crleight6" +
"\njhchtninehrvlsfvkr7two" +
"\n48ninetwo" +
"\n45fivefiveone2" +
"\nhthchfc1" +
"\noneninetwobfk7two" +
"\nninesevenkfnlhrznqseventhree9" +
"\n2fzbgjdvbnktwoonefivefiveqhz" +
"\nseven28mxjxnzb" +
"\ngqrznvtjeight9six277five" +
"\nfour3three" +
"\n1kpqmrjctwolngk8" +
"\n49zks" +
"\nthreesevensix9fivergmlzrblg" +
"\neight9sixeightlfvrbvfhd5one" +
"\n4sevensevenonegm6" +
"\nsix11one3lrztzsjczlnhddxbn" +
"\neightsevenpqdsxzmblmvdmjpeight9" +
"\n71seven" +
"\ncjqcqjlkgffoursvfcqxfkkszjhjl73" +
"\ndgndjkhcplztmkjrdn53" +
"\n1eight91vqjhmxrq9nine6" +
"\nbthlrtwo54hxppxfourdsnxnlnpvhmrpqtqzlr" +
"\n1bhdmvdrjvzthreenine6four6" +
"\nthreerknmhjtfourtwoeight65eight7" +
"\n1hbgvsdxtrsixmsfzxrlzskkkgh" +
"\n4hsjt" +
"\ntwothreefxhlr1bfngthreemthqqvgfpxeight" +
"\nnineeight4hp5nhksqdvrhcn22" +
"\nhdcfdknjkhsxnk9" +
"\npshjqxmqcbkhqkc5onekzfgkbeight" +
"\nfive3ninektmsrxhsdrseveneight1onenine" +
"\np5five" +
"\n2sixrgznrrvmxbbvnxhqtpeightthree77" +
"\nthreehmpjclsbhjlbxj1" +
"\n982" +
"\nvcjxvjvbmmzmrvv97one6rdxrdk" +
"\nfour8one9xpgfjgvjmdsevennineeight5" +
"\nfive7jmcrkbnine2" +
"\nkmbhc8threessdnfmsix" +
"\n214sixfkxkllldfive6" +
"\ndbhbfprsqkpmnfxgkgcone4qfgrgghqtqhxqn" +
"\n1plplklqjqjdsix" +
"\nztzgqsixqsevenseven4" +
"\n3threedjnbdbvxseven3qpsjone" +
"\ndnccnninetwomkzk52sixcgq" +
"\n94rdhfgjjr1gzl" +
"\n8three2ljbjjfvx" +
"\n8sdklzklt" +
"\nonexvrsttmhfninetftbrhtwo1gkpbninekh" +
"\nvsbfour5six" +
"\n2phhz85" +
"\ntwo73fourfive" +
"\n2twonineninesjkljpdgx" +
"\n2h" +
"\ntghzldzcj38foursix" +
"\n9srzlsv9seven" +
"\ntwojzssixfive53" +
"\n85eight35foursix" +
"\nrzx2lb" +
"\nghfnqk396nxqgvvgsmnine9hhc" +
"\n6sixnine746zlrksxcglg58" +
"\n1nbfivelvpcjnsddt3eight4fourblrzckjvf" +
"\nsixninethreednqkk9zzspxbcfjmfive" +
"\n16tsvqdplfnbnh" +
"\nl13tkbfldqcdfzjsdvtfttphmcmsix7" +
"\nrcgmlmnine94foureightnine" +
"\nlpvmrmtkthdqll5" +
"\ngjjprdvggvtjvqsnbg7xjvnp3eightninebhrdrq" +
"\nlzzmsmbpqnineninemnine6two4" +
"\n52qldxmrfive36ninetwo" +
"\nfour6fourhrsgf29" +
"\n9zb97kffl" +
"\neighttwonine5fourkqtjsjthree" +
"\ntwo21" +
"\ntwo6fourtjjn147" +
"\nlxnzlpcvzkbd9pxtr6qhbfmcmblbhmncljqd" +
"\nzccjlmzhm9" +
"\n11zdnjgj" +
"\none5fourone4onerttltxrzgf3" +
"\neight2nine83onepxjhx" +
"\n38fourllqpbclqnlmfourthree" +
"\ntreight9threesevenqgj" +
"\njb7threezfvnine28seven" +
"\nkmnkbmmnine53lddseven3" +
"\n3jxgfdzkgznine" +
"\n72lzbqmclqtwo94nkt5" +
"\nthreejdqnineeight4seven9two9" +
"\nsevenqnpjbznp6sevenfrnghcmvlfbns" +
"\noneone23oneeightone" +
"\n52qngdcmftmchfzt" +
"\ntwo8hnine1qsseven1three" +
"\nseventjlsdnmx25pnxvtxtsix4" +
"\n3veightjkgnbmcssevenpjrszdxqthree" +
"\nkkhxtnqzvz4jdqmtwoeight" +
"\n4eight15niner" +
"\nkreightpprcklznlcstjvqhn36ggfkphxdhm" +
"\nfour53ngjzlmhg" +
"\nztwoneoneshxnb2sevenxcrgjbckmfiveeight" +
"\n3five5221ddgprnvgpnj" +
"\n2hdkdzcvcmmtcrbsvfsevenone" +
"\ndtkjdncq73threechgcccdgqqsixthreehlfroneightn" +
"\nvtfvj4nine23seven2two" +
"\nphcvhvlq4kjnjcdkjrgninefourthreethree57" +
"\ntwopxngznkbrmrmrz7135one" +
"\none3bqdzone9sevenc2" +
"\n69threesix" +
"\n6jcmfivenine6fivefivethreetr" +
"\nsix1jpxjrqkpgllkqldf" +
"\nrjz4two59gjjgs2five" +
"\njoneight9gvqknfour7sevenfhzjsrldj" +
"\n9one4onesixhvvkqtpleightwovmh" +
"\nseven4threekpstdppxhvtwo7" +
"\nflxzfrxp1" +
"\nseven57eightthreeeightseveneight1" +
"\n6sevengmkvrvone" +
"\nfive1eightfour19" +
"\nnqxnqn7five3txrngheightnine" +
"\nrdfkkkthree7lnpmdgdb9" +
"\njhhvznhlsevenninefourcmkrbtfive3thtfbjvgvdnv" +
"\n2seven7eight8jrjkf4fourhv" +
"\noneone7hmdfjpzr57vfz" +
"\n7vqsllrhznvrdccrdrnjvmzmmknp4" +
"\n412sevenflfcvksjzk" +
"\n7eight43mq354oneightv" +
"\nsevenseven7eightoneightvvj" +
"\ntwotwosix2ninefour9three" +
"\nthreefourtwotwothree1lj" +
"\njpqccxztdninepncqqmnlxninexjfgvgccrm1" +
"\n5cr" +
"\njlhrrqmtlgtqfqpmkrhqjmpmxjshshblthreefournine2" +
"\nfour93kssrxr" +
"\nbztqzsjkeight6two18four" +
"\nsevenoneone587ghfbdmjpqxnpbh" +
"\n823onesevenseven1" +
"\ntt3qmcsbcm1eight" +
"\nprkptfivefourtwo8" +
"\n4six8836gmmgvlrz" +
"\nqklnpxjqhpczsc775" +
"\nphblxtj9" +
"\njgz8lrghthree813eightone" +
"\nvppt4eightthreezpgqt6dmxdtllksgrtmcbpfjh" +
"\nnine9lgsgzkjvbcmtfourr" +
"\n7three61ninefqgsfbpvjrx" +
"\n98ninenfzfh" +
"\ntwo2one8seventwo3hpdbstnhvkthree" +
"\nfourstrljqf8nine" +
"\n5kzgf5rspljfnsljrfrhg2mdsh" +
"\njkbjkbjhvfoureightgfnnxxnqh826z" +
"\n3ksgl" +
"\n3vfivehntm" +
"\nthreeeightone64krfskdqlxsfive" +
"\noneseventwo8vqzvnine9ninenq" +
"\n7fivesrkfkfthree8qmxmdrvhl" +
"\n447lhctbzpphthreebkmrthreetwo" +
"\ntwo92seven" +
"\n95sevenonecgj" +
"\nkcgsqqdpfhrpxzceight88" +
"\n9c4six" +
"\nrdkqfzkdlggfq661tfmqlgkcfmfcvpqsmr82" +
"\n1zzhzhz" +
"\nsix2ndsdxkfxsfthreeonesevenzlp" +
"\neight5threeoneightmxp" +
"\nsixfour4hdktht3two3seven" +
"\n9zdphltlnrfg9225" +
"\n6eightfourplxbgjfnnzfk2sevendcpbl" +
"\nthreenineeightsltsrkvpl28six8nine" +
"\nlmbqmrmjldlgb7" +
"\n2sixninedxnhmdfxh4five66" +
"\n5mllgtrxzkgxskkqxvpjttninefour3" +
"\n2hjl6two" +
"\nh5" +
"\neightthreethree3hcsrt" +
"\nhtjlplnfxgfqkm77seven" +
"\nlpmggpmcq943lcsvrhdljsqqdlgrphlnnine" +
"\n7twoonecgtdnfvlrsixrhnineseven" +
"\nlxszmkhj983five" +
"\nfour9fourninefourtwol" +
"\neight58sixsix94" +
"\n2sixthreefkbvtdgjq" +
"\n1rnc" +
"\n86seven13" +
"\none6f3jkrlrtf" +
"\ntwo4nine72twojtfive" +
"\nfourtdtwo27" +
"\ntwo6eight" +
"\nnxhzvln3five5" +
"\nsix7lbgqhnzkntwo" +
"\nhsfjgnjxjvzskjninezfndhtwofghpstbqzcseven1four" +
"\n6q" +
"\nffszknxdbqzgvmg2p" +
"\ncvl52" +
"\nnmfmp8six5threenhnxs4" +
"\n9fdknpvztworqfdpjrk36eight9" +
"\nbrmqzbhx84" +
"\ntwo72nvrlnhkjnineseven" +
"\n1spsmjscthone8" +
"\nsevenphkpdzvgzcjvlskdzbhqgpknrzdpsn39" +
"\ngfmxvrrvk8" +
"\n8zkpvrq7ggjskkr" +
"\n7ninemvm41sbftf6" +
"\nnine2sevenfiveonetlnhbbxv" +
"\nrtwone881998" +
"\neight5threegthree" +
"\nfhlnkzgqh191" +
"\n48fourcmfivecz" +
"\n5mdvbgmdhqbctxclonedhx1sevenqczd" +
"\n12one" +
"\nsixsixeightjmnbqzfive49bk" +
"\nnine2seventhreehvrfvm11" +
"\ngnsixb3three2" +
"\none3hrqzfsc3one8threehhjbzkmln" +
"\nvvxcbrrone95" +
"\nnine7twosnpv2threeeighttgg" +
"\n8onetwobqnxkkvhk5" +
"\nqrphvhfqninemcnzfrhfbvdtsnhst3" +
"\n2eightj" +
"\neightmdjmnqd1seven" +
"\nseven5sixtwoeightcglpqvlzxdfive32" +
"\nnine3scvsffour6" +
"\n3onefourseven" +
"\ncfqfkxv4five" +
"\n2dbq8fnzpzp" +
"\nfivekbblqgnjt12pxnvjxrssm" +
"\nsixfive16r8dqkgspmlb" +
"\nninexjhfsgn9ninezv" +
"\nlcfourtwofiveffrl6gfhxsrzmdl" +
"\n8oneshvxjn" +
"\n8threeeight8sixqbfnpxhr" +
"\nsmdjbhvsxlnhcqnxxgqcxfive5" +
"\nthreeonesevenglblr56lsntrdsjhp" +
"\nseven1ninevqpssj" +
"\n58seven" +
"\nlghxjdhpdbqs19" +
"\nlkcttrkrcpfourjtkfxmxcfive4kxnchspbqvqrfv" +
"\n7mpgnvdrmsqbcnfzrhtpjhz" +
"\nthreezkjqk5fourthree8four3" +
"\n7398" +
"\nxpmrcfffmhqpnmxtqxsblcd2fourq6eightdqvj" +
"\n6onedvdxtv9" +
"\nsevenzzvgmlqk5phcldhgghvshclp8" +
"\nxpddfttzsix63one3" +
"\nthreem5eightwomp" +
"\n2crrxnvrcjklzvdxk1slmrkq2" +
"\n5fivesix8mstzprjlvqhcrn" +
"\nrzkhdgfvkqonexhblnnine32" +
"\n5rseight377fivepnlsngxvmthree" +
"\nonesixseven9" +
"\n9dgr98" +
"\n6jjcb1hlmlchvtqhpp36nine" +
"\nlrxhvzs538seven76mkt" +
"\nsix48fivexqxqxdzzhggvcb1" +
"\n94seven7two7" +
"\nfive2bqxzjllksix4" +
"\n21three2eight" +
"\n9rbsrdjbgmgln2fivesixninejfvk1" +
"\n9foursixsevennine1" +
"\n9zjxdzqbxjlbbsnine" +
"\n8zfslsdlhdqmptwozzndjcskhptwo68" +
"\n9fiveone3fourpncrvfive9" +
"\ntbslbmgkqv936sixgsqzkfcjpl" +
"\nfournxfsgdthq4bsmp38sevenfivegclrlpgxt" +
"\n1kzql" +
"\n7onehfzqjdnlzcxflzrlxdh8four9mzf" +
"\n1sevensfivevgxeight9frcbzhpn" +
"\nfour1seven8njj8" +
"\n74dtgcn" +
"\nsevennine8twothreeztstwoklxhgfbgnnb" +
"\n7seven3bdrbpnzcr" +
"\n2twooneggtzrfqcsqqq" +
"\nrfxnrxkk5twocjddcmqbrqjvprtbdjtpngl99" +
"\npspkmpxzmn9cndplpjskthree7klc" +
"\neighthcnhhvvjxc295rxgfour" +
"\n74nine" +
"\njk17mxgfhjveight8twonine" +
"\n2six8seven2nine4sevenkrgmk" +
"\n6k96" +
"\n5jseveneight6eightnpfqt" +
"\nntwone1dkfrhmfourzngslfournine" +
"\nnine64" +
"\nnjeightwo52" +
"\n15mhnqxqcdgcqbqtdp" +
"\nhlpgsrxf429four" +
"\ntncmkps6bninergvfkrv649" +
"\nbqqlgvbdp3" +
"\n7sixpzpbrxbhqjgvgns" +
"\n849zhtmsevenfour77" +
"\nthree15seven9fourthreejfmxhllseven" +
"\nksixeight4three4fqkjthreemjqhxqgk" +
"\nfour4seven4eightkgsg" +
"\nsxgrghvnfknfrsixnkflvngkmsznhc8" +
"\n6dzxmxkvvpnkp6fnzdfkjsevendlqrsgdztone" +
"\neighttwo81cbrtrrfour9fourqkkbk" +
"\nhvnjpcxhlb9skfjsixseven9two9" +
"\npmt113onertkj4" +
"\nseveneightdftwotttone6" +
"\nfnsmzpthreexcssct42" +
"\n5eight4threefgllrpsgqhdtsqbqvzxtpgpdgnvctt" +
"\nrfddtbdpftrvf641five2x" +
"\n1three8clseventjtwodlhggr" +
"\nfivelxhrninej8fjngzdskseveneight" +
"\nninexxlhmhzdj7tfzds3khvctlrxmhsxdnbm" +
"\nbggglk31threefivenineonepqcdzczjm" +
"\n223seveneightfp" +
"\nmkvsblkv76" +
"\n7three86" +
"\nxkmxnbmtzrpdp2threesixfjkpbhpzb" +
"\n9four2" +
"\n7tqqg" +
"\nthree4five" +
"\nzndhqdmkntwo6" +
"\nrgblqcvrxzv5clzjdmfkph5" +
"\nskcvbd2seven5" +
"\neight8xnlmzm" +
"\n9twovfnvrmcfhn2gm187" +
"\nseven8sevenjshjndsdgrnczlsevensix7djrk" +
"\nbt2one4jgztwo" +
"\none126eightnzpxkgfj" +
"\nblrlnfnnvbhkltmgqqsixsix2bdnprfp2rpqtnvbtwonenpx" +
"\nprffzmfndlqfqjncvskgdtwovmbqnxm8twojttxpv2" +
"\n6qhjdzs5bm" +
"\n76lcmfntskmxddthreesixone23" +
"\nbstcghjbhkrlpxf1six" +
"\n7ptpcjchcfffivenineoneone" +
"\n7ninethreezstzpdr1two" +
"\nszxlzxpn2fiverhjrp" +
"\n5625" +
"\ntwo6ghnhfvrzlqdtqflvfgldfjj37gcxnxf" +
"\none3scnfcdpsn2five3ninejbv" +
"\neight569nffztptqgd1mqbkssdcppjg" +
"\nfbsvjlln4cdshlvmxpmmc4threemfqnseven" +
"\nnljzcfzfive5ninen" +
"\ngmhlb2sixfive55cvnkgknrpbdtnrd" +
"\n47six" +
"\nskkhbxfour6trmh7nineseven" +
"\nthree9five" +
"\n12ninexcc" +
"\neight6kdtbvfourb" +
"\n425threetwo4hxnxseven" +
"\nfive4jbbftjkcmjqxrdls3nlhvcgeightrjn3" +
"\nknnjdj5tgtsrgnmjqmjjrnht1" +
"\nnine3mhxxsix39" +
"\nfivefourseven2drz3eight" +
"\n215xnm" +
"\n6seven3" +
"\n77kqzfcbklvznhgvnpfivefivejx5" +
"\n8seven6sevengjssbvngxzbgcmm1" +
"\nmqqxqgmzdvzdgjrlkntdjhgfouronegrkddl14" +
"\n5threetxbscpfxdgfive" +
"\ntwo3bdhxhkqnd87cmrkzxf5" +
"\ntwo7twobgnxklp" +
"\n9sdnnzrkms8rbbzfqms8one" +
"\n2hxdxxstwo" +
"\nfoursrb7smqxmkt" +
"\n14xfhdkfmh" +
"\n84trqvtltpqvdtzdlch" +
"\n19hjjhfljxnine" +
"\n1lbkvjcjbbeightngnqdvz8nddkmqmvvb8seven" +
"\nmlnpptcflthdprj4fiveseven92sdhxchdcj" +
"\ncdmbfivepgdbgdfvbklz8six7" +
"\ncbqvbtpljv8skzgmbzbfgrbffmmb" +
"\none9ninev4" +
"\nnzvjsqx7fivebgptkrxsx65sixfivesczbl" +
"\n42bhjthree1" +
"\ntwoqnsxllxrsfive64vgtpcmxc9" +
"\nsixbzflbdv7" +
"\n54threehf9vhctwofour" +
"\n4pmkmlpnnine3" +
"\n3sk88qglhbsjxdsdcnqrnpdz" +
"\n79szleighttwofivef" +
"\nvbctcrttwo43oneone" +
"\nqjhdlqzqftfgxgnbbscsbznfgslbltd6szdppxfpm" +
"\nfivenbbsgfthree9" +
"\nhjqmr9rqsrhspcfjmfj379" +
"\nlxjeightwo6four8" +
"\n45twonkxhqq" +
"\nggcvxfz6lfpbcspvzsqztjllrrpd" +
"\nqmlvh9bmlkfive83fivepbtnine" +
"\n1qqqbrct45sevenx" +
"\nttgtbnzrn1dprs6four" +
"\nnine1rcstjdlhb6hsrnvsjxeight1" +
"\ngtlhk3gjhqvtwotv" +
"\nsix278kd" +
"\nvlgzjxlmfs6" +
"\n8d51" +
"\nseven6lzjgcc" +
"\nsz7sixctstdkhlb89" +
"\n27three" +
"\n6two3msmszdzcrfgxj5" +
"\n8dbvzcrqv" +
"\ntftbmjrjd831gbzrhscthree6jvvfour" +
"\n254sevensixzzkjsq1jmmbvdbhtmfjsp" +
"\nghqgzfkqhnqntwo4nfj1" +
"\nsixfourninetwoxjtsxcr3" +
"\nfive2niner2" +
"\n22blmbkts7" +
"\none2cbkvqstone5threekzvskbzdt5" +
"\n48lgvmpjvhlfsixone6seventwo9" +
"\n1five5pzglqpqltn" +
"\n8dc6blpnqcjndthree5" +
"\nlncn3sevenptdrlpqsbseven" +
"\n9mdzt" +
"\nflnr3sevensevenpjgrgdbrvdgkhtlzzljdnppp" +
"\nlpljgkpqdgqsevenseven8foureight5" +
"\nxzrkml7" +
"\n127" +
"\nhgxdcdprhg4qkxtwo1rlc" +
"\nnine9five5g" +
"\nthree1lgdctzmqpgc4zbmc6ttsls" +
"\nonethree495three" +
"\neightfblxhxptkdnhk6npbbsxgxlhoneights" +
"\nfourm6sixeightmrztnbjptqfv" +
"\ntwoone76" +
"\n6dsbcqrjj" +
"\npfkoneightmv8bdrmhlnhmninektnbdtvtwo6twod" +
"\nqttsnrppd6s" +
"\n76three5" +
"\nthrxlfmbmtsxjzsx5fivelvknrgctp5vlmpf" +
"\nnine7ninethreeztmlsfch" +
"\n18eightthreetwo978seven" +
"\nbseightwovtlxsb5sevensrqnrklqvzstncmr6zg" +
"\n3zthdrzlqcjbdsfgqphkzqeight" +
"\nmvfnine6sevenrkbxbhlld35five" +
"\ncddpxjhdgt9fsfmkxmvtm3dnqndzsnm" +
"\nvrhjfsfkt3sevenqcsxvkdrfndtfljvkxzckctwoonednpklkm" +
"\nhqjfnbh9threexqfive" +
"\nmrpdsqbhzjzplrlqf4fjstqq" +
"\n6htcxzghbx" +
"\nnine6dflrcbjl65" +
"\nbpclpbkbbmq9threeonetwonejn" +
"\neight5fivedcsqtsnfkthreefour9six" +
"\n4lvl" +
"\nfourq2" +
"\nfour388rrkjtfjzrceight8" +
"\n7lznsixfh41pdlvhbh9tr" +
"\n9nineseven438" +
"\ntgcqntlpqonevmcqninezcxfxbbone6" +
"\nseven2gg" +
"\ntwo1one65threexsix" +
"\n1one6lrgflmsixfivefour" +
"\nsevenone46" +
"\n61crvnncdxmkseventzqvdsmfkx" +
"\nkhztxzpnl6nine" +
"\nthreeonehjxpgj3nine6threehcsix" +
"\ntwotwo5mpbgbtfjpcxbksix49two" +
"\n62" +
"\nkssevengjcdtrcmklxdgftslsz7kfclxsdtc" +
"\n9mgpqjhlfivesix34sevenone" +
"\n89711" +
"\n3tgkpfrvvcpxfs8jhmdcxz392" +
"\n6ghbglhfive469x" +
"\n9ctfqkhbgprf38" +
"\ncshsctcqr6tcxzjgrzsx" +
"\nchn5onethreevqdhhdv74" +
"\none9fmlbplqeightfthchbzjhzgkbv" +
"\nfourtwopkllbslsix94bcshtp2" +
"\nrvmpsxkmcqninetwovhjzvhm3" +
"\n4eightbcdvjjr5ninethree6fiveone" +
"\n6three6eightdqkcg" +
"\nrsix7seven6fdpzpgvmkp" +
"\neightrvlmbdq91six" +
"\nx978bsdxxnknine" +
"\n81five3" +
"\n6bmmvdflqfxcmhtsixjprt" +
"\nfive6two4five37seven7" +
"\nnine6hldzbzxhzdvnptjeight4ninejxlhvtkpzd" +
"\neightfone9" +
"\n4vknnxxj6192q6nnfbcm" +
"\ntwolzt6two23two1" +
"\n84lltlrz4vsl3two" +
"\nrnfour39cpcggzone" +
"\nhgfx464" +
"\n6tdldmclkhqkkdzxmhvtthree8" +
"\n9sevensix" +
"\npfgb55" +
"\nmqnqnineplccphpctvxs3sldkl" +
"\ncblchzhrsone4fcbvfxkjjbcptp8oneightv" +
"\n5mndn" +
"\npptwone8" +
"\nfivejvzddb3bcvvskzxstfive5" +
"\nk7sevenninefivefiveqzbxlsgcmoneone" +
"\ngxqthreejzntslggzhxnsevensix1onecphllcxc" +
"\n6slttzsdvnkfgbqldqvlqrszlpsixtwo3" +
"\n7lqlkstbxpt87xcbssmn" +
"\nfourtwoeightjnflkkbksn566" +
"\ndkjpckbtnninejcxg3" +
"\n6713ninetwo" +
"\n9six3rskfprrbqhbstmp9" +
"\n4onepfqshseven4seven" +
"\n1d" +
"\nzdht4sksmztjpcrjthreenine" +
"\nfour29one2csmk" +
"\n93lmdlxrrj4threeeight" +
"\nzkbckninedlzxpmdneight4" +
"\ngjdshxctnszcrlxj8" +
"\n4nqfvtshhk" +
"\nhvjvrh37threehznzlrprtptwo4one" +
"\neightghbtgpbjfdprqnpvhhcbdtrzsjgsix2" +
"\nsixmgpzcmxq3sixsixxpdrfpzdsmqsr" +
"\nonefivegphhdggf6kdrmnvgfqj" +
"\nmvtj2six" +
"\n6jhtqngl7jtphdsvtkbvscm1fivehv" +
"\n632onefiveeight2" +
"\n9ninezfbzdplrfourthree3eight8" +
"\n164three7fbznchn8" +
"\nfsklrdzbzv8threefour8sevensix" +
"\ntwosixtwo4sixsevenfivethree" +
"\nfoursevensix4fourxhfjzjbkhsix" +
"\neight26foursixseven" +
"\n8frxqhzqstxzmlsqpqtcsevenfive9" +
"\nmgck4815plnnmrvhfvhbsln" +
"\n3fxpccfplrfivetwobbngonephjs9four" +
"\n4gbbgpbqnpbqjzgvjrgpprtwoqvjrrn" +
"\nfour17two93eightthree" +
"\ntwoseven3" +
"\none5vqpmvkpgtwo88seven" +
"\nsssmblvsixseven2" +
"\n6fsdxfxgdhnqkcpzmbljlfkfsjztdp94h" +
"\nkx99pbk6" +
"\nnineone7knpqj" +
"\n2fourzgseightseven5" +
"\nsixninekdbvrrllrl8sevencvrdhnine" +
"\n8jtqlpz2" +
"\nhgblktnine92htpggp22" +
"\n8l3" +
"\nxfxb82srqlldfonelqjhssmsrfkbmldjqt2klnq" +
"\n321one42seventhreenlrtm" +
"\njponefoureight6nine" +
"\n3lsljdntnsjrseven" +
"\ntwo1rvc9fiveonerkdnrnfd1" +
"\n1twoclddjfsixtwovhhczl" +
"\n4two48krlhhbvzhq" +
"\n78fourncglqhghzxhbrb98threeglzklqgkg" +
"\nthreetmzvnrfnqq23" +
"\n9five5four5ones8" +
"\nsix4onefive6" +
"\n45lfmdrgsrvkkkzglnqmrlt" +
"\n64onevthree" +
"\nonefour9zvkgndsv2" +
"\ndmrk46vlrztxbjfsbll" +
"\n2four8oneeighteight" +
"\npqtvvlbrgninethreeone1" +
"\n6four733d" +
"\nseven1qhxhgxsx8fzlbkm9hpmnqkknjpseven" +
"\n6cspj21fivetwo" +
"\nseven3fllzkctljxlcqljbxfrcleightwov" +
"\n73bkkkdnptddqqxhjteight" +
"\njjdmnfourp1threextxpmdnnnine" +
"\nfive2lvhh4kfg3" +
"\nrbconeightthree8" +
"\n59lqvpccqlbmqqtzfourseven547" +
"\nvdvsbhcptvxbgd46three6" +
"\nxtrbzgtwofour9kq9" +
"\n2nineeight" +
"\n29nlcdzgrkh7" +
"\nonehglhgkcksm2onemzpnqmbxccvpxxssg1gcpvhl" +
"\nsevenhhhgntcldxlfbrpks27threeeightwoh" +
"\n2kccbsjdblthree" +
"\nnine6threenine" +
"\nnkbcdbseven8cqfour" +
"\nbfour3" +
"\nnineeighttneight833" +
"\n3glgsvfhkz7fivefivefive" +
"\nzzlxqlfour3mcjjp" +
"\n93eight28" +
"\n1threeffive4c5oneightgdg" +
"\nfive4six" +
"\ngpzjjxthree4fmvbzmzbjf31six" +
"\nbcbdtbjrtn3five11" +
"\nkbtnkjvkmdh6" +
"\nfpjsqbxv5" +
"\n3twofive" +
"\n9vplnvkkmhpdfxckm2js64" +
"\n4eightsixxgmbxzkkcsevennvdgprqcgvsqct" +
"\neightsix1five8one5sevenvqjmrkdjq" +
"\n9seven7" +
"\nngmnllfj49dlqdmnthree" +
"\nsixthreeqbkmzvmt7sbgsscqsg" +
"\n5sjbrdqvbksss7gnfcp6vjpbfcgps" +
"\nnhssblqsixtwo57" +
"\nfourbthree7four" +
"\n6foursix" +
"\npfcbeightfvtnlrmld273" +
"\nfivefhthree8189mvhf" +
"\nnine5qzvxjvj1nkljhvdpnf9" +
"\ntgrllhmcmpmpeightzjd7" +
"\nvnblzqbhx4four6" +
"\n5qb6six2one9" +
"\nsevenprjnnznl9nvbfour28sixnpxttwonemcn" +
"\n4sixsix" +
"\n7two9" +
"\n7pzzdv2fourgxxczzqtdxfjgtxjztbvjt" +
"\n218jxfvzrfournine" +
"\n4sevennine" +
"\n662onecvzlsixzj7six" +
"\nbpnmf95seven2" +
"\nclfcfivetwo9mkxqnthnnhkpxcm" +
"\nklgfmtjlctstwo9" +
"\n1zlqhkkhmdvszg2three4nljlbrzz" +
"\nfive6threesevensnprfgsggs1nqqjtsqxpdtjlfr" +
"\nnhkvqk89four" +
"\nrtgzhbhjcjcznp5cxbprzxfoureighteight4lng" +
"\nxdvgfzxbvzfdkff5dthree" +
"\n1two465sixnine" +
"\n2six327mflsr" +
"\nqpeightwo4sixfivetwokvzhkg" +
"\n4seven9jmbnjrhrtthree" +
"\n4flchcfh1four" +
"\n94fourldjgvg7drlcxqtnv2" +
"\n99sevenfourmfhnjg9" +
"\n32fivesix275ninelpmkponeightnp" +
"\n9xzgfxcmplrzjsbnlkgcbnpchth" +
"\nhtoneighttntmj6ninethreen7" +
"\n64one9sevenghcqjjrseven" +
"\n8nvkfqkbbpzseven63zpnbbnine62" +
"\nfivefoursmdnvczb6" +
"\nmmrqfrtwo2hhpk7eightthree" +
"\ndnrrfklrpxstln57vqzkrxlqnmsvmgdbthreeoneightc" +
"\n19rqmvljqfrmfoureightseven" +
"\ntwofive9vm1csqlrvngtfiveeight" +
"\nzeightwofivefour6gcmh97" +
"\n7pzts" +
"\n42ninecnbthreedlgglgp" +
"\n3kqthqfprdntgbfqqc" +
"\nsixdrrqxxdgl8dhf4" +
"\n51three" +
"\n39qpctcjfnh7" +
"\n9bfour4" +
"\nonefourseventwohbqpxn73" +
"\njzbqdcsevenseven8seven8mmbktn" +
"\nxlzeightwo3648threegrfourrjzvz" +
"\neighttmmtcrqhlpnrjjlchrvvthree6" +
"\n5five3one69eightthf" +
"\nbctwonelppl122bkfivetwo" +
"\nfoursix2ddxqqz" +
"\nhbmcnbvdhpkhp3sv88" +
"\ncsdp3onebjxxlckthreetwoplskdphhmp" +
"\nrvkdmmgfvsfive8ggvcvxgjgrsix" +
"\n7zjsdzbeightfour7" +
"\nfour3qfsvmbhhfv276" +
"\nkrdnine4bnneightbpxfdvl9pcf" +
"\nscdklgdh46fivefiveseven24seven" +
"\n9rmmsthreethrlxjtjkb" +
"\n7fivesevenstfourfivecddbzmxrrqeight" +
"\nfivethreeninexgkpmpbvsix7" +
"\nsixvqpdpfk43rhmd9" +
"\n2zvkhxtfourpdfnsbsnbvone" +
"\nfour7lrcvtsczdp2sixvvlkzrzzk9gcxtmx7" +
"\n61pzlq74cmlkjvseven" +
"\nqcjzncctvv237dsjvqm2three" +
"\n89threezgd2eight8" +
"\nnxll6fivev6kt4rmtfkrnkfive" +
"\nlvxxvnpzlrk8sbmbnhtmlds" +
"\nsevensevenjhcxcninesevendlghdvfj5mkmdb" +
"\nvfq4" +
"\ngxkcbkknqg8187eight" +
"\nsix79tcdlv" +
"\nbsntwone3six8" +
"\n8nd" +
"\nqdlhkvvpxrtgbrzpmcfourfivegpjqjfbfmngnnbpshfkdpsdgj2" +
"\nthreetjbcjmzlcvnchp34nineseven" +
"\nzjpxzkdlmhcbzkrflvfour5mdqldvgrnx5sixlmgjpqx" +
"\ncjnvmsdrpmq8" +
"\nthreeqr8xrxgv87" +
"\nrcfsntqrlonezlgl7dhlflqckc9vhd21" +
"\n9three7three" +
"\nptkqnrtmrnsixfiveseven67" +
"\n44fourfive9" +
"\n4fstrhjjctsvrz7cpbr6gjpkkxglx" +
"\n6rjqcmpfbp" +
"\n731" +
"\nfivexdfkzmjs3146five6kvdsnvsxsj" +
"\ndhhz6" +
"\nsltpllcs4seven8771" +
"\n1fourkjfhfcfxbeightseven8three" +
"\nsevengrzlghdkg8three" +
"\nsixsixnkgfcfivekqfzsj59" +
"\n4qbqggqlmjkrgnrxthree9dxgssjkrseven" +
"\nxhlmbone3one8" +
"\n3t" +
"\n8six37" +
"\nfivethree3onegthree9thhfzp" +
"\n9xdmvkx7fourfxpgsvnine77" +
"\nconeightfivedfkqrfjcckghzsrtrc9sevenone1" +
"\nfive4ninevxldttfxxdfxfhttbxkvjkfour23" +
"\ncpfklzcpp2eightfjqcrsmhlnxckxmtdchbzqblqsqqp" +
"\n34six1" +
"\n5fivex4" +
"\nfivefivepjfrpzdvcq2" +
"\nonelnppnxczthreelldqndvt3" +
"\nnine699ninexjnine" +
"\n16one74" +
"\n8jdkblqbq59zlkhj97one" +
"\nckrft6sixeight" +
"\nfourldmq24" +
"\n87zvt" +
"\nthreefiveone75hxnqqsjroneeight" +
"\nlsxlzvssshlvbr5vtvgsznrxhkp73" +
"\nthreeknpqxxgg84" +
"\noneone3mvtlxjhfiveksgpnms9kzkf" +
"\nthxrqsrninefourfive31kbcp57" +
"\nfivesixnine6oneqgxckbjqfszpsvhjgms" +
"\neightsix83" +
"\nttwone9qqhg7" +
"\n7fhvffiveftkbfgxsdfourthree1" +
"\nhbkst6foursixdndhmtwosix" +
"\nmhgxpvgmndjgsftqjkkxkfzxmhgtdpxxmbztwo6six" +
"\ntwo6ljpjc8ffgmblpxrcsevenvbsm" +
"\nxqbmzh85mqchftctnfourfkeight7" +
"\nxlbltdqcsx2sixmqdzvxhqj" +
"\neight468" +
"\nnine2rcrgfpx5" +
"\neight5tjoneseven" +
"\nhncnnjvbdfdfcthree1" +
"\nsixzfllx24threesevensix" +
"\n7eighteight" +
"\n8652sslmpr1" +
"\nm88ktthbnh5" +
"\nsix1ninethree" +
"\nsevengtb6" +
"\n9eightzpdkqzp3" +
"\ntplshfhqsshs4" +
"\n4twothreefpj" +
"\n48threetwockbzxdhqp4eight" +
"\neightmkeightjdgmvxdqfx7" +
"\nsix99" +
"\n69one" +
"\ntwodmnzphhsb2" +
"\nthree3zhqckdqeight1" +
"\n2x9xjzgtdgk5ninefourseven" +
"\n4vrpseven7tq" +
"\n86cjqrqp" +
"\none8four67" +
"\nthree7two7six2kxl" +
"\nbhnbkthreetwofqchzvbxjqqm4seven4five" +
"\nonehncctk2qnphtkjns" +
"\n6stmbmtj1ms" +
"\nmdhmknhftkdtnrgkbmh7six1six" +
"\nsix4three5" +
"\nfnccxltjdn4gteightfourone3" +
"\ntwofoureight5seven4" +
"\nfour7twosix8three" +
"\npgvjtszlkx4" +
"\nthreeseven438two5" +
"\nsix78qhspmhqtkc" +
"\n56sevenjdfvfbzvsgthreemrbmcqctgonesixppg" +
"\nfivesevenlsixvgxfkxtbclkbsqt35" +
"\nsixeightfiveseven7three" +
"\nfrmgthreefour3szxtf1" +
"\n5eightrvflvtqzq8sevenj" +
"\nfive5dbtfxqxzfour52mxfzmkfks" +
"\n2ggjtsdmdr6" +
"\ncpszsjthree4" +
"\nrrd8rrfcvzhcdr651rfc6h" +
"\nsfnfsc89eighttmsc888t" +
"\n46eight" +
"\n992sevenzsxkzxxppnkxlxkpbz" +
"\nseven93tzgthree" +
"\n952sszqqqrc1seven" +
"\nfivetwo3sevenfive4" +
"\npfgdhlvv23onesixtwoznfrlcndlvr8" +
"\nmhcvnl1three5" +
"\n3twofour3pgjtjp2five1" +
"\nnfcvxxcltwo49khnmggcdlr5" +
"\n8frh21n" +
"\n6p477xtfrhvclvnxpbdmftrgd2" +
"\nsevenbqsdxlceight3" +
"\nseven2nine86jx" +
"\n44cqv" +
"\n7bfgmrc" +
"\n88twoonethree4m5oneightn" +
"\n94eightthreefourdqdrnx8threetwonepbt" +
"\nonegvkdxllnd76" +
"\nonechljqc4mvhljvcgbthree" +
"\n2ninenine1two" +
"\nthreenineone8ggnbmnfcnfteightsix1" +
"\neight6fivermqnm94onessnplzpkzjm" +
"\n7fivezcnlhtfournine" +
"\npfourvpqfqz7foursix" +
"\nsevenonedcs9" +
"\nthreebfspz4b6sevennzkznbd7" +
"\ntbg56jzgmkgmxnbncvtgrpk4" +
"\n337sdxdlbqd2" +
"\n4tcvrpvqkkhhthmcjzggqgmpdonektzmrrszs" +
"\ntwocfgqtp7" +
"\nsevenfcmgkblzh4mvgjmktn4" +
"\nptnqxxf1two" +
"\nfqftxjznine186three" +
"\n6foursevenonenjkbdjfbhhtvdthreethreeeight" +
"\n4two3" +
"\nzhronethree2six3five7" +
"\n3fxbqvvkh6twoneftm" +
"\nzf2two4xndhkmb93" +
"\nfivefivefour9rhcjxxtbtd63nxtk" +
"\nfive3qpvgdcqcvcvbn6" +
"\n1qjckjqkbqvbtqkrbvkxp" +
"\n2gnglzbllksix6fgfjrrltrhrspl5seven" +
"\nfour6five8gpktxzxcdtvqsevenqlbsnine" +
"\nseven6lgkknlfouronegxnine2" +
"\n9ninefour8fourpd2threetwo" +
"\n358lmjlsevensjrlhkbspkqxcfourmktxqrhjz" +
"\nmbqnmgjcbninenine82djlmzk38" +
"\nfour6lgd66eighteight8" +
"\nthree566" +
"\nczeightwoninefive7one" +
"\nthreecmkmzszq337rsctbvvpgvlfvreight" +
"\nbtwone91blrcbjvpfl" +
"\ncgfddzmnmz3" +
"\nseven3sixsixnqt9" +
"\nxsthfourtwo1nine5dpvjpnine" +
"\n97fpjzktsixtzpdseven5" +
"\nseven6fivefive" +
"\ntwo16" +
"\nnddxvnqnggdzcnhthree2" +
"\n1sixseven" +
"\nthree1nvpdzhrndgbvfiveeight1" +
"\n134" +
"\nthreeeightlvbp6" +
"\nqmrmqcjkdfoursixfive8915six" +
"\n2jrsix78twoninefour" +
"\n5vgtsevenfoureighttmntdgptbvxonez" +
"\n2npzxnpmdtxctgeightrbvrgdkqthree5fg" +
"\nhxtvnvqffivekgzcl6dtmplhqprfdbzdoneninesix" +
"\ntwo384zlqs8351" +
"\n2sevensgnxgzkqsixtwo" +
"\nnkone877fivegtr" +
"\nldr43" +
"\nsix3nrstcpvfive6" +
"\none799onenineseven" +
"\n4onetwofourfourghpzmgjthree" +
"\none53two8tnmlpcxvvqvrtjthreefour" +
"\n49nine" +
"\nsgnxr3two" +
"\nthreeblnc1six3hvdlj1" +
"\n8sskxtzkl35hknine8one" +
"\nkeightcqbkbz9gsbxdqshzngxcbjqtqn" +
"\n7foursixnine" +
"\nsbhv3lvkgsgk" +
"\ndmvthree152cjh" +
"\ntwo6nzdd7rrltcngdbshfzlhsix" +
"\n1nxthreetchfsleightq6v" +
"\n5threevrc9four6st" +
"\nb2threeeightonesix44hnxzcm" +
"\n2threefourfournine" +
"\n1fxbbfszjhseven" +
"\nlrxhhqdzx2sixsixtwo7eight6nine" +
"\n2eightmzzcgszpxr" +
"\n7nine7sevenzndthknx1" +
"\nkkstmkvmfeight92ninelpxhsssk9" +
"\n1zjpvbmzdxxc" +
"\nninevtqgtzxtprbst1bxxsrrrztnhbjrdqvlheightvbhncs" +
"\n7seven8threeeight" +
"\nmfzkktfoneseven8pvqpszgqjszx" +
"\nlr9kddzcxmmxc253lxfournine" +
"\nthree29gpbvjthree6hcnxzqcdcj" +
"\nsixljtcnxbq8vnbrjgd9qsqonethreenzdnvjjg" +
"\nvpeightwo15" +
"\nlctthree6four14nine" +
"\neightfiveone47sevenhdxtlninegffpzhjmh" +
"\nfoursixhtx9nineseven8" +
"\nseven94four" +
"\n9h6nine" +
"\nfivemxkfxvbpneight8hqlmmrmeight6" +
"\nfive5bhrghlfiveseventhreeoneseven" +
"\neight79nbmspstpkxhttvrq" +
"\nxqcmqxnine6" +
"\nprcnjkshkvlcgsixfiveone6" +
"\nbtbcs2rsrcrshzp8six89" +
"\n5tg578fldlcxponefourtwonet" +
"\nv4" +
"\ngqrnpz5sth" +
"\nxcsmcfour3eightts" +
"\neight691seven8cxdbveightzv" +
"\nonenjhcd9";
	
	var outputs = new List<int>();
	var lines = input.Split(new char[]{'\n', '\r'});
	
	foreach(var line in lines)
	{
		outputs.Add(ProcessLine(line));
	}
	outputs.Dump();
	outputs.Sum(x => x).Dump();
}

private Dictionary<string, int> _numbers = new Dictionary<string, int> {
	{"one", 1},
	{"two", 2},
	{"three", 3},
	{"four", 4},
	{"five", 5},
	{"six", 6},
	{"seven", 7},
	{"eight", 8},
	{"nine", 9},
};

private int ProcessLine(string line)
{
	var firstNumber = 0;
	var storedNumber = 0;
	
	var numbersInLine = _numbers.Keys.Where(n => line.Contains(n)).ToArray();
	//numbersInLine.Dump();
	for (var charNum = 0; charNum < line.Length; charNum++)
	{
		var character = line[charNum];
		
		if(numbersInLine.Any())
		{
			var numbersFromChar = numbersInLine.ToArray();
			
			var stop = false;
			for(var j = 0; ((j + charNum < line.Length) && (!stop)); j++)
			{
				var c = line[j+charNum];
				numbersFromChar = numbersFromChar.Where(n => n[j] == c).ToArray();

				if(!numbersFromChar.Any())
				{ stop = true; }
				
				if(numbersFromChar.Length == 1 )
				{
					//numbersFromChar.Dump();
					if(line.Length > numbersFromChar[0].Length + charNum - 1
						&& line.Substring(charNum, numbersFromChar[0].Length).Equals(numbersFromChar[0]))
					{ 
						stop=true;
						var cn = _numbers[numbersFromChar[0]];
						//charNum += numbersFromChar[0].Length - 1;
						if(firstNumber == 0)
						{	
							firstNumber = cn;
							
							continue;
						}
						
						storedNumber = cn;
					}
				}
			}
		}
		
		if((int)character < 48 
			|| (int) character > 57)
	    {
	        continue;
	    }
		
	    var currentNumber = (int)character - 48;
		if(firstNumber == 0){
			firstNumber = currentNumber;
			continue;
		}
		
	    storedNumber = currentNumber;
	}
	if(storedNumber == 0) { storedNumber = firstNumber; }
	return firstNumber * 10 + storedNumber; 
}
